default:
  options:
    gfxbackend: gl
    video_threaded: true
    # menu retroarch
    retroarch.menu_driver: ozone
    retroarch.menu_scale_factor: "1.500000"
    retroarch.audio_driver: alsathread

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
n64:
  emulator: libretro
  core:     parallel_n64
